# Generated by Django 4.2.7 on 2023-11-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_gender_profile_height_profile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], max_length=100, null=True, verbose_name='activity level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_goal',
            field=models.CharField(blank=True, choices=[('gain_weight', 'Gain Weight'), ('stay_lean', 'Stay Lean'), ('cut', 'Cut')], max_length=100, null=True, verbose_name='weight goal'),
        ),
    ]
