# Generated by Django 4.2.7 on 2023-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], default='sedentary', max_length=100, verbose_name='activity level'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_goal',
            field=models.CharField(choices=[('gain_weight', 'Gain Weight'), ('stay_lean', 'Stay Lean'), ('cut', 'Cut')], default='gain_weight', max_length=100, verbose_name='weight goal'),
        ),
    ]
