# Generated by Django 4.2.7 on 2023-11-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_profile_activity_level_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_advice',
            field=models.TextField(blank=True, null=True, verbose_name='ChatGPT advice'),
        ),
    ]
