# Generated by Django 4.2.7 on 2023-11-09 11:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_profile_chat_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chat_advice',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=10000, verbose_name='chat advice'),
        ),
    ]
