# Generated by Django 4.2.7 on 2023-11-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_alter_profile_chat_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_advice_generated',
            field=models.BooleanField(default=False, verbose_name='Chat advice generated'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_advice_regeneration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last advice regeneration'),
        ),
    ]
