# Generated by Django 4.2.7 on 2023-11-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_remove_profile_chat_advice_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_left',
            field=models.DurationField(blank=True, null=True, verbose_name='Time left until next advice generation'),
        ),
    ]
