# Generated by Django 4.2.7 on 2023-11-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_profile_time_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time_left',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timeleft till regenerating'),
        ),
    ]
