# Generated by Django 4.2.7 on 2023-11-17 06:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=10000, verbose_name='content'),
        ),
    ]
